name: CI/CD - API (Azure Functions)

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/api-deploy.yml"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      # (optionnel) tests si tu en as pour l'API
      # - name: Test
      #   run: npm test

      - name: Azure Login (RBAC)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTIONAPP_NAME }}
          package: "."
