name: Deploy Front (SWA) # Nom du workflow affiché dans GitHub Actions

on:
  push: # Déclencheur : à chaque push
    branches: ["master"] # uniquement si le push concerne "master"
    paths:
      - "frontend/bayroumeter-frontend/**" # uniquement si le frontend change
      - ".github/workflows/swa.yml" # ou si ce workflow change

jobs:
  build-deploy: # Nom du job
    runs-on: ubuntu-latest # Runner GitHub : VM Linux

    defaults:
      run:
        working-directory: frontend/bayroumeter-frontend # Toutes les commandes s’exécutent depuis le frontend

    steps:
      - uses: actions/checkout@v4 # Récupère le code source

      - name: Deploy to Azure Static Web Apps (upload only)
        uses: Azure/static-web-apps-deploy@v1 # Action officielle de déploiement SWA
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }} # Injecte l’URL de ton API comme variable d’env pour le build
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }} # Token généré par Azure SWA (stocké en secret GitHub)
          app_location: "frontend/bayroumeter-frontend" # Dossier racine du frontend
          output_location: ".next" # Dossier de sortie après build Next.js
          action: "upload" # Mode upload uniquement (on ne rebuild pas l’API)
          production_branch: "master" # Branche de prod
          api_location: "" # Vide = pas d’API gérée par SWA (car séparée dans Azure Functions)
          skip_api_build: true # Empêche de reconstruire l’API intégrée
