name: Deploy Front (SWA)

on:
  push:
    branches: ["master"]
    paths:
      - "frontend/bayroumeter-frontend/**"
      - ".github/workflows/swa.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/bayroumeter-frontend

    steps:
      - uses: actions/checkout@v4


      - name: Deploy to Azure Static Web Apps (upload only)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }}
          app_location: "frontend/bayroumeter-frontend"
          output_location: ".next"
          action: "upload"
          production_branch: "master"
          api_location: ""
          skip_api_build: true